import 'obd_pid.dart';

final Map<int, ObdPid> pidRegistry = {
  0x04: ObdPid(
    id: 0x04,
    name: "Carga do Motor",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x05: ObdPid(
    id: 0x05,
    name: "Temp. Arrefecimento",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x06: ObdPid(
    id: 0x06,
    name: "Ajuste Combustível Curto (B1)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => ((b[0] * 100) / 128) - 100,
  ),
  0x07: ObdPid(
    id: 0x07,
    name: "Ajuste Combustível Longo (B1)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => ((b[0] * 100) / 128) - 100,
  ),
  0x0B: ObdPid(
    id: 0x0B,
    name: "Pressão Admissão (MAP)",
    unit: "kPa",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x0C: ObdPid(
    id: 0x0C,
    name: "Rotação do Motor (RPM)",
    unit: "RPM",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 4,
  ),
  0x0D: ObdPid(
    id: 0x0D,
    name: "Velocidade",
    unit: "km/h",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x0E: ObdPid(
    id: 0x0E,
    name: "Avanço Ignição",
    unit: "°",
    expectedBytes: 1,
    calculate: (b) => (b[0] / 2) - 64,
  ),
  0x0F: ObdPid(
    id: 0x0F,
    name: "Temp. Ar Admissão",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x10: ObdPid(
    id: 0x10,
    name: "Fluxo de Ar (MAF)",
    unit: "g/s",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 100,
  ),
  0x11: ObdPid(
    id: 0x11,
    name: "Posição Acelerador (TPS)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x21: ObdPid(
    id: 0x21,
    name: "Distância com Luz de Injeção",
    unit: "km",
    expectedBytes: 2,
    calculate: (b) => (b[0] * 256) + b[1].toDouble(),
  ),
  0x2F: ObdPid(
    id: 0x2F,
    name: "Nível Combustível",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x31: ObdPid(
    id: 0x31,
    name: "Distância após Limpeza de Erros",
    unit: "km",
    expectedBytes: 2,
    calculate: (b) => (b[0] * 256) + b[1].toDouble(),
  ),
  0x33: ObdPid(
    id: 0x33,
    name: "Pressão Barométrica Absoluta",
    unit: "kPa",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x42: ObdPid(
    id: 0x42,
    name: "Tensão Módulo Controle (ECU)",
    unit: "V",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 1000,
  ),
  0x46: ObdPid(
    id: 0x46,
    name: "Temp. Ar Ambiente",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x5A: ObdPid(
    id: 0x5A,
    name: "Posição Relativa Pedal Acelerador",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x5C: ObdPid(
    id: 0x5C,
    name: "Temperatura Óleo do Motor",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),

  // Siga exatamente esse padrão de 5 linhas para inserir os outros sensores da Wikipédia
};
