import '../obd_pid.dart';

final Map<int, ObdPid> pidRegistry = {
  0x04: ObdPid(
    id: 0x04,
    name: "Carga do Motor",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x05: ObdPid(
    id: 0x05,
    name: "Temp. Arrefecimento",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x06: ObdPid(
    id: 0x06,
    name: "Ajuste Combustível Curto (B1)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => ((b[0] * 100) / 128) - 100,
  ),
  0x07: ObdPid(
    id: 0x07,
    name: "Ajuste Combustível Longo (B1)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => ((b[0] * 100) / 128) - 100,
  ),
  0x0B: ObdPid(
    id: 0x0B,
    name: "Pressão Admissão (MAP)",
    unit: "kPa",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x0C: ObdPid(
    id: 0x0C,
    name: "Rotação do Motor (RPM)",
    unit: "RPM",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 4,
  ),
  0x0D: ObdPid(
    id: 0x0D,
    name: "Velocidade",
    unit: "km/h",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x0E: ObdPid(
    id: 0x0E,
    name: "Avanço Ignição",
    unit: "°",
    expectedBytes: 1,
    calculate: (b) => (b[0] / 2) - 64,
  ),
  0x0F: ObdPid(
    id: 0x0F,
    name: "Temp. Ar Admissão",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x10: ObdPid(
    id: 0x10,
    name: "Fluxo de Ar (MAF)",
    unit: "g/s",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 100,
  ),
  0x11: ObdPid(
    id: 0x11,
    name: "Posição Acelerador (TPS)",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x21: ObdPid(
    id: 0x21,
    name: "Distância com Luz de Injeção",
    unit: "km",
    expectedBytes: 2,
    calculate: (b) => (b[0] * 256) + b[1].toDouble(),
  ),
  0x2F: ObdPid(
    id: 0x2F,
    name: "Nível Combustível",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x31: ObdPid(
    id: 0x31,
    name: "Distância após Limpeza de Erros",
    unit: "km",
    expectedBytes: 2,
    calculate: (b) => (b[0] * 256) + b[1].toDouble(),
  ),
  0x33: ObdPid(
    id: 0x33,
    name: "Pressão Barométrica Absoluta",
    unit: "kPa",
    expectedBytes: 1,
    calculate: (b) => b[0].toDouble(),
  ),
  0x42: ObdPid(
    id: 0x42,
    name: "Tensão Módulo Controle (ECU)",
    unit: "V",
    expectedBytes: 2,
    calculate: (b) => ((b[0] * 256) + b[1]) / 1000,
  ),
  0x46: ObdPid(
    id: 0x46,
    name: "Temp. Ar Ambiente",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),
  0x5A: ObdPid(
    id: 0x5A,
    name: "Posição Relativa Pedal Acelerador",
    unit: "%",
    expectedBytes: 1,
    calculate: (b) => (b[0] * 100) / 255,
  ),
  0x5C: ObdPid(
    id: 0x5C,
    name: "Temperatura Óleo do Motor",
    unit: "°C",
    expectedBytes: 1,
    calculate: (b) => (b[0] - 40).toDouble(),
  ),

  // Siga exatamente esse padrão de 5 linhas para inserir os outros sensores da Wikipédia
  // Dicionário com os nomes dos sensores mais comuns em português
  /* final Map<int, String> _pidNames = {
    // Grupo 01 a 20
    0x01: "Status dos Monitores de Emissão",
    0x03: "Status do Sistema de Combustível",
    0x04: "Carga Calculada do Motor",
    0x05: "Temperatura do Líquido de Arrefecimento",
    0x06: "Ajuste de Combustível a Curto Prazo (Banco 1)",
    0x07: "Ajuste de Combustível a Longo Prazo (Banco 1)",
    0x0B: "Pressão Absoluta do Coletor (MAP)",
    0x0C: "Rotação do Motor (RPM)",
    0x0D: "Velocidade do Veículo",
    0x0E: "Avanço do Ponto de Ignição",
    0x0F: "Temperatura do Ar de Admissão",
    0x10: "Taxa de Fluxo de Ar (MAF)",
    0x11: "Posição do Acelerador (TPS)",
    0x13: "Sensores de Oxigênio Presentes (Sonda Lambda)",
    0x1C: "Padrão OBD suportado",
    0x1F: "Tempo de Funcionamento do Motor",

    // Grupo 21 a 40
    0x21: "Distância Percorrida com Luz de Injeção Acesa",
    0x2E: "Purga Evaporativa Comandada",
    0x2F: "Nível do Tanque de Combustível",
    0x30: "Aquecimentos desde que os erros foram limpos",
    0x31: "Distância percorrida desde a limpeza de erros",
    0x32: "Pressão de Vapor do Sistema Evaporativo",
    0x33: "Pressão Atmosférica Absoluta",

    // Grupo 41 a 60
    0x41: "Status do Monitor no Ciclo de Direção Atual",
    0x42: "Tensão do Módulo de Controle (ECU)",
    0x43: "Valor Absoluto da Carga do Motor",
    0x44: "Relação Ar/Combustível Comandada",
    0x45: "Posição Relativa do Acelerador",
    0x46: "Temperatura do Ar Ambiente",
    0x47: "Posição Absoluta do Acelerador B",
    0x49: "Posição do Pedal do Acelerador D",
    0x4A: "Posição do Pedal do Acelerador E",
    0x4C: "Atuador do Acelerador Comandado",
    0x51: "Tipo de Combustível do Veículo",
    0x5C: "Temperatura do Óleo do Motor",
  }; */
};
